djangoproject/blog/urls.py
from django.urls import path 
from .views import(
    home,
    about,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    ) 

app_name = 'blog'

urlpatterns = [
    # path('',home,name='blog-home'),
    path('',PostListView.as_view(),name='home'),
    path('user/<str:username>',UserPostListView.as_view(),name='user-posts'),
    path('post/<int:pk>/',PostDetailView.as_view(),name='post-detail'),
    path('post/<int:pk>/update',PostUpdateView.as_view(),name='post-update'),
    path('post/<int:pk>/delete',PostDeleteView.as_view(),name='post-delete'),
    path('post/new/',PostCreateView.as_view(),name='post-create'),
    path('about/',about,name='about'),
]

djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views

# static file setting for developement: Serving files uploaded by user during development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='users-register'),
    path('profile/',user_views.profile,name='users-profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='users-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'),name='users-logout'),
    path('',include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    
 

djangoproject/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PostModel(models.Model):
  author = models.ForeignKey(User,on_delete=models.CASCADE)  
  title = models.CharField(max_length=100)
  content = models.TextField()
  date_posted = models.DateTimeField(default=timezone.now) 
  # auto_now=True=>date change everytime post updated, good for last modified field
  # auto_now_add=True => you cannot change the value of the date posted
  # user.postmodel_set.all()
  # user.postmodel_set.create(title='blog helas',content='lela')  # author will be this user
  

  def __str__(self):
      return self.title
  
  # Done for class base createview to redirect to the detail view of the newly
  # created post
  def get_absolute_url(self):
      return reverse("blog:post-detail", kwargs={"pk": self.pk})
  
  

  







# python manage.py sqlmigrate blog 0001

djangoproject/blog/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.http import HttpResponse
from .models import PostModel
from django.views.generic import (
  ListView,
  DetailView,
  CreateView,
  UpdateView,
  DeleteView)


# Home View
def home(request):
  context = {
    'posts': PostModel.objects.all(),
    'current':True
  }
  return render(request,'blog/home.html',context)



class PostListView(ListView):
  model = PostModel
  # search for <app>/<model>_<viewtype>.html but can be replace with a specific template
  template_name = 'blog/home.html'  

  # object_list si the default List that is set from ListView, in this case
  # it can be changed to post since the template was already built with posts List
  context_object_name = 'posts'

  # add ordering on the query_set of ListView, the query_set is ran automatically 
  # even though it is not added in code block of PostListView
  ordering = ['-date_posted']  # get the lastest post

  # Add pagination :
  #  https://docs.djangoproject.com/en/3.0/topics/pagination/#using-paginator-in-view
  # /objects/?page=3
  # /objects/?page=last
  # path('objects/page<int:page>/', PaginatedView.as_view()), 
  paginate_by = 5


class UserPostListView(ListView):
  model = PostModel
  template_name = 'blog/user_posts.html'
  context_object_name = 'posts'
  paginate_by = 5


  def get_queryset(self):
    user = get_object_or_404(User,username=self.kwargs.get('username'))
    return PostModel.objects.filter(author=user).order_by('-date_posted')





class PostDetailView(DetailView):
  # search for <app>/<model>_<viewtype>.html = blog/postmodel_detail.html
  # object is the single data on the template
  model = PostModel




# The CreateView page displayed to a GET request uses a template_name_suffix of '_form'. For example, changing this attribute to '_create_form' for a view creating objects for the example Author model would cause the default template_name to be 'myapp/author_create_form.html'.
class PostCreateView(LoginRequiredMixin,CreateView):
  model = PostModel
  fields = ['title','content']

  # In case you would like to redirect to home page without using the detailview as default
  # success_url = '/'   

  # overwrite the form valid method
  # since the author of the block is unknown we need to add the author
  def form_valid(self, form):
    form.instance.author = self.request.user
    return super().form_valid(form)   # then validate the form

 



# The UpdateView page displayed to a GET request uses a template_name_suffix of '_form'. For example, changing this attribute to '_update_form' for a view updating objects for the example Author model would cause the default template_name to be 'myapp/author_update_form.html'.
class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
  model = PostModel
  fields = ['title','content']

  def form_valid(self,form):
    form.instance.author =  self.request.user
    return super().form_valid(form)
  
  # check if the current user is the author of the post before updating
  # must be called test_func() from UserPassesTestMixin
  def test_func(self):
    # get the current post
    post = self.get_object()
    if self.request.user == post.author:
      return True
    return False





# The DeleteView page displayed to a GET request uses a template_name_suffix of '_confirm_delete'. For example, changing this attribute to '_check_delete' for a view deleting objects for the example Author model would cause the default template_name to be 'myapp/author_check_delete.html'.
class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
  model = PostModel
  success_url = reverse_lazy('blog:home')
  

  def test_func(self):
    # get the current post
    post = self.get_object()
    if self.request.user == post.author:
      return True
    return False










# About View
def about(request):
  return render(request,'blog/about.html',{'title':'About','current':True})

djangoproject/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
  <h1>About Page</h1>
{% endblock content %}

djangoproject/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
   <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">  
    <!-- Static CSS -->
    <link rel="stylesheet" href="{% static 'blog/main.css' %}" type="text/css">

  {% if title %}
    <title>Django Blog-{{title}}</title>
  {% else %}
    <title>Django Blog</title>
  {% endif %}
  
</head>
<body>
      <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'blog:home' %}">Django Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto"> 
            <a class="nav-item nav-link " href="{% url 'blog:home' %}">Home</a>
            <a class="nav-item nav-link " href="{% url 'blog:about' %}">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'blog:post-create' %}">New Post</a>
              <a class="nav-item nav-link" href="{% url 'users-profile' %}">Profile</a> 
              <a class="nav-item nav-link" href="{% url 'users-logout' %}">Logout</a>
                {% if user.is_staff%}
                  <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
                {% endif %}
              
            {% else %}
              <a class="nav-item nav-link" href="{% url 'users-login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'users-register' %}">Register</a>
              
            {% endif %}
            
            
          </div>
        </div>
      </div>
    </nav>
  </header>
   <main role="main" class="container">
  <div class="row">
    <div class="col-md-8">

      {% if messages %}
         {% for message in messages %}
           <div class="alert alert-{{message.tags}}">
            {{message}}
           </div>
         {% endfor %}
      {% endif %}

      {% block content %}
         <!-- Website content goes here -->
      {% endblock content %}

    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>
     



<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

djangoproject/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
  {% for post in posts %}
        <article class="media content-section">
        <img src="{{post.author.profileuser.image.url}}" class="rounded-circle article-img ">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:'F d,Y' }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
       </article>
  {% endfor %}

  <!-- If pagination is add on the view -->
  {% if is_paginated %}

     <!-- page.obj is the page obj passed in the template -->
    {% if page_obj.has_previous %}
      <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
      <a href="?page={{ page_obj.previous_page_number}}" class="btn btn-outline-info mb-4">Previous</a>
    {% endif %}
     

     {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
           <a href="?page={{num}}" class="btn btn-info mb-4">{{num}}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a href="?page={{num}}" class="btn btn-outline-info mb-4">{{num}}</a>
        {% endif %}
     {% endfor %}



     {% if page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}" class="btn btn-outline-info mb-4">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages}}" class="btn btn-outline-info mb-4">Last</a>
    {% endif %}


 

  {% endif %}

{% endblock content %}

    

djangoproject/blog/templates/blog/postmodel_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
  <div class="content-section">
    <form method="POST">
       {% csrf_token %}
        <fieldset class="for-group">
           <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{object.title}}"</h2>
        </fieldset>
        <div class="form-group">
         <button type="submit" class="btn btn-outline-danger">Yes,Delete</button>
         <a  class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id  %}">Cancel</a>
        </div>
    </form>
  </div>
{% endblock content %}

djangoproject/blog/templates/blog/postmodel_detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <article class="media content-section">
  <img src="{{object.author.profileuser.image.url}}" class="rounded-circle article-img ">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:'F d,Y' }}</small>
        {% if object.author == user %}
          <div>
            <a href="{% url 'blog:post-update' object.id %} " class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
            <a href="{% url 'blog:post-delete' object.id %} " class="btn btn-danger btn-sm mt-1 mb-1">Delete</a>
          </div> 
        {% endif %} 
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
{% endblock content %}

    

djangoproject/blog/templates/blog/postmodel_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST">
       {% csrf_token %}
        <fieldset class="for-group">
           <legend class="border-bottom mb-4">Blog Post</legend>
           {{form |crispy }}
        </fieldset>
        <div class="form-group">
         <button type="submit" class="btn btn-outline-info">Post</button>
        </div>
    </form>
  </div>
{% endblock content %}

djangoproject/blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}

{% block content %}
<h1 class="mb-3" >Posts By {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
  {% for post in posts %}
        <article class="media content-section">
        <img src="{{post.author.profileuser.image.url}}" class="rounded-circle article-img ">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:'F d,Y' }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
       </article>
  {% endfor %}



  <!-- If pagination is add on the view -->
  {% if is_paginated %}

     <!-- page.obj is the page obj passed in the template -->
    {% if page_obj.has_previous %}
      <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
      <a href="?page={{ page_obj.previous_page_number}}" class="btn btn-outline-info mb-4">Previous</a>
    {% endif %}
     

     {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
           <a href="?page={{num}}" class="btn btn-info mb-4">{{num}}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a href="?page={{num}}" class="btn btn-outline-info mb-4">{{num}}</a>
        {% endif %}
     {% endfor %}



     {% if page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}" class="btn btn-outline-info mb-4">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages}}" class="btn btn-outline-info mb-4">Last</a>
    {% endif %}


 

  {% endif %}

{% endblock content %}

    